volumes:
  postgres-volume:

services:
  postgres:
    image: postgres:latest
    container_name: vacancies-aggregator-postgres
    volumes:
      - postgres-volume:/var/lib/pgsql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vacancies-aggregator
